-- ================================================
-- COMPREHENSIVE COUNTRIES SEED DATA
-- ================================================
-- Complete list of 195 countries with ISO codes, currencies, phone prefixes, and flags
-- This will populate the countries table with all recognized countries

-- Clear existing data if needed (uncomment if you want to start fresh)
-- DELETE FROM countries;

-- Insert all 195 countries
INSERT INTO countries (code, name, iso3_code, continent, currency_code, phone_prefix, flag_emoji, popular) VALUES
-- Popular travel destinations first
('AE', 'United Arab Emirates', 'ARE', 'Asia', 'AED', '+971', '🇦🇪', TRUE),
('US', 'United States', 'USA', 'North America', 'USD', '+1', '🇺🇸', TRUE),
('GB', 'United Kingdom', 'GBR', 'Europe', 'GBP', '+44', '🇬🇧', TRUE),
('FR', 'France', 'FRA', 'Europe', 'EUR', '+33', '🇫🇷', TRUE),
('ES', 'Spain', 'ESP', 'Europe', 'EUR', '+34', '🇪🇸', TRUE),
('IT', 'Italy', 'ITA', 'Europe', 'EUR', '+39', '🇮🇹', TRUE),
('DE', 'Germany', 'DEU', 'Europe', 'EUR', '+49', '🇩🇪', TRUE),
('IN', 'India', 'IND', 'Asia', 'INR', '+91', '🇮🇳', TRUE),
('TH', 'Thailand', 'THA', 'Asia', 'THB', '+66', '🇹🇭', TRUE),
('SG', 'Singapore', 'SGP', 'Asia', 'SGD', '+65', '🇸🇬', TRUE),
('JP', 'Japan', 'JPN', 'Asia', 'JPY', '+81', '🇯🇵', TRUE),
('AU', 'Australia', 'AUS', 'Oceania', 'AUD', '+61', '🇦🇺', TRUE),
('GR', 'Greece', 'GRC', 'Europe', 'EUR', '+30', '🇬🇷', TRUE),
('TR', 'Turkey', 'TUR', 'Asia', 'TRY', '+90', '🇹🇷', TRUE),
('CH', 'Switzerland', 'CHE', 'Europe', 'CHF', '+41', '🇨🇭', TRUE),
('NL', 'Netherlands', 'NLD', 'Europe', 'EUR', '+31', '🇳🇱', TRUE),
('CA', 'Canada', 'CAN', 'North America', 'CAD', '+1', '🇨🇦', TRUE),
('MY', 'Malaysia', 'MYS', 'Asia', 'MYR', '+60', '🇲🇾', TRUE),
('ID', 'Indonesia', 'IDN', 'Asia', 'IDR', '+62', '🇮🇩', TRUE),

-- All other countries alphabetically
('AF', 'Afghanistan', 'AFG', 'Asia', 'AFN', '+93', '🇦🇫', FALSE),
('AL', 'Albania', 'ALB', 'Europe', 'ALL', '+355', '🇦🇱', FALSE),
('DZ', 'Algeria', 'DZA', 'Africa', 'DZD', '+213', '🇩🇿', FALSE),
('AD', 'Andorra', 'AND', 'Europe', 'EUR', '+376', '🇦🇩', FALSE),
('AO', 'Angola', 'AGO', 'Africa', 'AOA', '+244', '🇦🇴', FALSE),
('AG', 'Antigua and Barbuda', 'ATG', 'North America', 'XCD', '+1268', '🇦🇬', FALSE),
('AR', 'Argentina', 'ARG', 'South America', 'ARS', '+54', '🇦🇷', FALSE),
('AM', 'Armenia', 'ARM', 'Asia', 'AMD', '+374', '🇦🇲', FALSE),
('AT', 'Austria', 'AUT', 'Europe', 'EUR', '+43', '🇦🇹', FALSE),
('AZ', 'Azerbaijan', 'AZE', 'Asia', 'AZN', '+994', '🇦🇿', FALSE),
('BS', 'Bahamas', 'BHS', 'North America', 'BSD', '+1242', '🇧🇸', FALSE),
('BH', 'Bahrain', 'BHR', 'Asia', 'BHD', '+973', '🇧🇭', FALSE),
('BD', 'Bangladesh', 'BGD', 'Asia', 'BDT', '+880', '🇧🇩', FALSE),
('BB', 'Barbados', 'BRB', 'North America', 'BBD', '+1246', '🇧🇧', FALSE),
('BY', 'Belarus', 'BLR', 'Europe', 'BYN', '+375', '🇧🇾', FALSE),
('BE', 'Belgium', 'BEL', 'Europe', 'EUR', '+32', '🇧🇪', FALSE),
('BZ', 'Belize', 'BLZ', 'North America', 'BZD', '+501', '🇧🇿', FALSE),
('BJ', 'Benin', 'BEN', 'Africa', 'XOF', '+229', '🇧🇯', FALSE),
('BT', 'Bhutan', 'BTN', 'Asia', 'BTN', '+975', '🇧🇹', FALSE),
('BO', 'Bolivia', 'BOL', 'South America', 'BOB', '+591', '🇧🇴', FALSE),
('BA', 'Bosnia and Herzegovina', 'BIH', 'Europe', 'BAM', '+387', '🇧🇦', FALSE),
('BW', 'Botswana', 'BWA', 'Africa', 'BWP', '+267', '🇧🇼', FALSE),
('BR', 'Brazil', 'BRA', 'South America', 'BRL', '+55', '🇧🇷', FALSE),
('BN', 'Brunei', 'BRN', 'Asia', 'BND', '+673', '🇧🇳', FALSE),
('BG', 'Bulgaria', 'BGR', 'Europe', 'BGN', '+359', '🇧🇬', FALSE),
('BF', 'Burkina Faso', 'BFA', 'Africa', 'XOF', '+226', '🇧🇫', FALSE),
('BI', 'Burundi', 'BDI', 'Africa', 'BIF', '+257', '🇧🇮', FALSE),
('CV', 'Cabo Verde', 'CPV', 'Africa', 'CVE', '+238', '🇨🇻', FALSE),
('KH', 'Cambodia', 'KHM', 'Asia', 'KHR', '+855', '🇰🇭', FALSE),
('CM', 'Cameroon', 'CMR', 'Africa', 'XAF', '+237', '🇨🇲', FALSE),
('CF', 'Central African Republic', 'CAF', 'Africa', 'XAF', '+236', '🇨🇫', FALSE),
('TD', 'Chad', 'TCD', 'Africa', 'XAF', '+235', '🇹🇩', FALSE),
('CL', 'Chile', 'CHL', 'South America', 'CLP', '+56', '🇨🇱', FALSE),
('CN', 'China', 'CHN', 'Asia', 'CNY', '+86', '🇨🇳', FALSE),
('CO', 'Colombia', 'COL', 'South America', 'COP', '+57', '🇨🇴', FALSE),
('KM', 'Comoros', 'COM', 'Africa', 'KMF', '+269', '🇰🇲', FALSE),
('CG', 'Congo', 'COG', 'Africa', 'XAF', '+242', '🇨🇬', FALSE),
('CD', 'Democratic Republic of the Congo', 'COD', 'Africa', 'CDF', '+243', '🇨🇩', FALSE),
('CR', 'Costa Rica', 'CRI', 'North America', 'CRC', '+506', '🇨🇷', FALSE),
('CI', 'Côte d''Ivoire', 'CIV', 'Africa', 'XOF', '+225', '🇨🇮', FALSE),
('HR', 'Croatia', 'HRV', 'Europe', 'EUR', '+385', '🇭🇷', FALSE),
('CU', 'Cuba', 'CUB', 'North America', 'CUP', '+53', '🇨🇺', FALSE),
('CY', 'Cyprus', 'CYP', 'Europe', 'EUR', '+357', '🇨🇾', FALSE),
('CZ', 'Czech Republic', 'CZE', 'Europe', 'CZK', '+420', '🇨🇿', FALSE),
('DK', 'Denmark', 'DNK', 'Europe', 'DKK', '+45', '🇩🇰', FALSE),
('DJ', 'Djibouti', 'DJI', 'Africa', 'DJF', '+253', '🇩🇯', FALSE),
('DM', 'Dominica', 'DMA', 'North America', 'XCD', '+1767', '🇩🇲', FALSE),
('DO', 'Dominican Republic', 'DOM', 'North America', 'DOP', '+1809', '🇩🇴', FALSE),
('EC', 'Ecuador', 'ECU', 'South America', 'USD', '+593', '🇪🇨', FALSE),
('EG', 'Egypt', 'EGY', 'Africa', 'EGP', '+20', '🇪🇬', FALSE),
('SV', 'El Salvador', 'SLV', 'North America', 'USD', '+503', '🇸🇻', FALSE),
('GQ', 'Equatorial Guinea', 'GNQ', 'Africa', 'XAF', '+240', '🇬🇶', FALSE),
('ER', 'Eritrea', 'ERI', 'Africa', 'ERN', '+291', '🇪🇷', FALSE),
('EE', 'Estonia', 'EST', 'Europe', 'EUR', '+372', '🇪🇪', FALSE),
('SZ', 'Eswatini', 'SWZ', 'Africa', 'SZL', '+268', '🇸🇿', FALSE),
('ET', 'Ethiopia', 'ETH', 'Africa', 'ETB', '+251', '🇪🇹', FALSE),
('FJ', 'Fiji', 'FJI', 'Oceania', 'FJD', '+679', '🇫🇯', FALSE),
('FI', 'Finland', 'FIN', 'Europe', 'EUR', '+358', '🇫🇮', FALSE),
('GA', 'Gabon', 'GAB', 'Africa', 'XAF', '+241', '🇬🇦', FALSE),
('GM', 'Gambia', 'GMB', 'Africa', 'GMD', '+220', '🇬🇲', FALSE),
('GE', 'Georgia', 'GEO', 'Asia', 'GEL', '+995', '🇬🇪', FALSE),
('GH', 'Ghana', 'GHA', 'Africa', 'GHS', '+233', '🇬🇭', FALSE),
('GD', 'Grenada', 'GRD', 'North America', 'XCD', '+1473', '🇬🇩', FALSE),
('GT', 'Guatemala', 'GTM', 'North America', 'GTQ', '+502', '🇬🇹', FALSE),
('GN', 'Guinea', 'GIN', 'Africa', 'GNF', '+224', '🇬🇳', FALSE),
('GW', 'Guinea-Bissau', 'GNB', 'Africa', 'XOF', '+245', '🇬🇼', FALSE),
('GY', 'Guyana', 'GUY', 'South America', 'GYD', '+592', '🇬🇾', FALSE),
('HT', 'Haiti', 'HTI', 'North America', 'HTG', '+509', '🇭🇹', FALSE),
('HN', 'Honduras', 'HND', 'North America', 'HNL', '+504', '🇭🇳', FALSE),
('HU', 'Hungary', 'HUN', 'Europe', 'HUF', '+36', '🇭🇺', FALSE),
('IS', 'Iceland', 'ISL', 'Europe', 'ISK', '+354', '🇮🇸', FALSE),
('IR', 'Iran', 'IRN', 'Asia', 'IRR', '+98', '🇮🇷', FALSE),
('IQ', 'Iraq', 'IRQ', 'Asia', 'IQD', '+964', '🇮🇶', FALSE),
('IE', 'Ireland', 'IRL', 'Europe', 'EUR', '+353', '🇮🇪', FALSE),
('IL', 'Israel', 'ISR', 'Asia', 'ILS', '+972', '🇮🇱', FALSE),
('JM', 'Jamaica', 'JAM', 'North America', 'JMD', '+1876', '🇯🇲', FALSE),
('JO', 'Jordan', 'JOR', 'Asia', 'JOD', '+962', '🇯🇴', FALSE),
('KZ', 'Kazakhstan', 'KAZ', 'Asia', 'KZT', '+7', '🇰🇿', FALSE),
('KE', 'Kenya', 'KEN', 'Africa', 'KES', '+254', '🇰🇪', FALSE),
('KI', 'Kiribati', 'KIR', 'Oceania', 'AUD', '+686', '🇰🇮', FALSE),
('KP', 'North Korea', 'PRK', 'Asia', 'KPW', '+850', '🇰🇵', FALSE),
('KR', 'South Korea', 'KOR', 'Asia', 'KRW', '+82', '🇰🇷', FALSE),
('KW', 'Kuwait', 'KWT', 'Asia', 'KWD', '+965', '🇰🇼', FALSE),
('KG', 'Kyrgyzstan', 'KGZ', 'Asia', 'KGS', '+996', '🇰🇬', FALSE),
('LA', 'Laos', 'LAO', 'Asia', 'LAK', '+856', '🇱🇦', FALSE),
('LV', 'Latvia', 'LVA', 'Europe', 'EUR', '+371', '🇱🇻', FALSE),
('LB', 'Lebanon', 'LBN', 'Asia', 'LBP', '+961', '🇱🇧', FALSE),
('LS', 'Lesotho', 'LSO', 'Africa', 'LSL', '+266', '🇱🇸', FALSE),
('LR', 'Liberia', 'LBR', 'Africa', 'LRD', '+231', '🇱🇷', FALSE),
('LY', 'Libya', 'LBY', 'Africa', 'LYD', '+218', '🇱🇾', FALSE),
('LI', 'Liechtenstein', 'LIE', 'Europe', 'CHF', '+423', '🇱🇮', FALSE),
('LT', 'Lithuania', 'LTU', 'Europe', 'EUR', '+370', '🇱🇹', FALSE),
('LU', 'Luxembourg', 'LUX', 'Europe', 'EUR', '+352', '🇱🇺', FALSE),
('MG', 'Madagascar', 'MDG', 'Africa', 'MGA', '+261', '🇲🇬', FALSE),
('MW', 'Malawi', 'MWI', 'Africa', 'MWK', '+265', '🇲🇼', FALSE),
('MV', 'Maldives', 'MDV', 'Asia', 'MVR', '+960', '🇲🇻', FALSE),
('ML', 'Mali', 'MLI', 'Africa', 'XOF', '+223', '🇲🇱', FALSE),
('MT', 'Malta', 'MLT', 'Europe', 'EUR', '+356', '🇲🇹', FALSE),
('MH', 'Marshall Islands', 'MHL', 'Oceania', 'USD', '+692', '🇲🇭', FALSE),
('MR', 'Mauritania', 'MRT', 'Africa', 'MRU', '+222', '🇲🇷', FALSE),
('MU', 'Mauritius', 'MUS', 'Africa', 'MUR', '+230', '🇲🇺', FALSE),
('MX', 'Mexico', 'MEX', 'North America', 'MXN', '+52', '🇲🇽', FALSE),
('FM', 'Micronesia', 'FSM', 'Oceania', 'USD', '+691', '🇫🇲', FALSE),
('MD', 'Moldova', 'MDA', 'Europe', 'MDL', '+373', '🇲🇩', FALSE),
('MC', 'Monaco', 'MCO', 'Europe', 'EUR', '+377', '🇲🇨', FALSE),
('MN', 'Mongolia', 'MNG', 'Asia', 'MNT', '+976', '🇲🇳', FALSE),
('ME', 'Montenegro', 'MNE', 'Europe', 'EUR', '+382', '🇲🇪', FALSE),
('MA', 'Morocco', 'MAR', 'Africa', 'MAD', '+212', '🇲🇦', FALSE),
('MZ', 'Mozambique', 'MOZ', 'Africa', 'MZN', '+258', '🇲🇿', FALSE),
('MM', 'Myanmar', 'MMR', 'Asia', 'MMK', '+95', '🇲🇲', FALSE),
('NA', 'Namibia', 'NAM', 'Africa', 'NAD', '+264', '🇳🇦', FALSE),
('NR', 'Nauru', 'NRU', 'Oceania', 'AUD', '+674', '🇳🇷', FALSE),
('NP', 'Nepal', 'NPL', 'Asia', 'NPR', '+977', '🇳🇵', FALSE),
('NZ', 'New Zealand', 'NZL', 'Oceania', 'NZD', '+64', '🇳🇿', FALSE),
('NI', 'Nicaragua', 'NIC', 'North America', 'NIO', '+505', '🇳🇮', FALSE),
('NE', 'Niger', 'NER', 'Africa', 'XOF', '+227', '🇳🇪', FALSE),
('NG', 'Nigeria', 'NGA', 'Africa', 'NGN', '+234', '🇳🇬', FALSE),
('MK', 'North Macedonia', 'MKD', 'Europe', 'MKD', '+389', '🇲🇰', FALSE),
('NO', 'Norway', 'NOR', 'Europe', 'NOK', '+47', '🇳🇴', FALSE),
('OM', 'Oman', 'OMN', 'Asia', 'OMR', '+968', '🇴🇲', FALSE),
('PK', 'Pakistan', 'PAK', 'Asia', 'PKR', '+92', '🇵🇰', FALSE),
('PW', 'Palau', 'PLW', 'Oceania', 'USD', '+680', '🇵🇼', FALSE),
('PA', 'Panama', 'PAN', 'North America', 'PAB', '+507', '🇵🇦', FALSE),
('PG', 'Papua New Guinea', 'PNG', 'Oceania', 'PGK', '+675', '🇵🇬', FALSE),
('PY', 'Paraguay', 'PRY', 'South America', 'PYG', '+595', '🇵🇾', FALSE),
('PE', 'Peru', 'PER', 'South America', 'PEN', '+51', '🇵🇪', FALSE),
('PH', 'Philippines', 'PHL', 'Asia', 'PHP', '+63', '🇵🇭', FALSE),
('PL', 'Poland', 'POL', 'Europe', 'PLN', '+48', '🇵🇱', FALSE),
('PT', 'Portugal', 'PRT', 'Europe', 'EUR', '+351', '🇵🇹', FALSE),
('QA', 'Qatar', 'QAT', 'Asia', 'QAR', '+974', '🇶🇦', FALSE),
('RO', 'Romania', 'ROU', 'Europe', 'RON', '+40', '🇷🇴', FALSE),
('RU', 'Russia', 'RUS', 'Europe', 'RUB', '+7', '🇷🇺', FALSE),
('RW', 'Rwanda', 'RWA', 'Africa', 'RWF', '+250', '🇷🇼', FALSE),
('KN', 'Saint Kitts and Nevis', 'KNA', 'North America', 'XCD', '+1869', '🇰🇳', FALSE),
('LC', 'Saint Lucia', 'LCA', 'North America', 'XCD', '+1758', '🇱🇨', FALSE),
('VC', 'Saint Vincent and the Grenadines', 'VCT', 'North America', 'XCD', '+1784', '🇻🇨', FALSE),
('WS', 'Samoa', 'WSM', 'Oceania', 'WST', '+685', '🇼🇸', FALSE),
('SM', 'San Marino', 'SMR', 'Europe', 'EUR', '+378', '🇸🇲', FALSE),
('ST', 'São Tomé and Príncipe', 'STP', 'Africa', 'STN', '+239', '🇸🇹', FALSE),
('SA', 'Saudi Arabia', 'SAU', 'Asia', 'SAR', '+966', '🇸🇦', FALSE),
('SN', 'Senegal', 'SEN', 'Africa', 'XOF', '+221', '🇸🇳', FALSE),
('RS', 'Serbia', 'SRB', 'Europe', 'RSD', '+381', '🇷🇸', FALSE),
('SC', 'Seychelles', 'SYC', 'Africa', 'SCR', '+248', '🇸🇨', FALSE),
('SL', 'Sierra Leone', 'SLE', 'Africa', 'SLL', '+232', '🇸🇱', FALSE),
('SK', 'Slovakia', 'SVK', 'Europe', 'EUR', '+421', '🇸🇰', FALSE),
('SI', 'Slovenia', 'SVN', 'Europe', 'EUR', '+386', '🇸🇮', FALSE),
('SB', 'Solomon Islands', 'SLB', 'Oceania', 'SBD', '+677', '🇸🇧', FALSE),
('SO', 'Somalia', 'SOM', 'Africa', 'SOS', '+252', '🇸🇴', FALSE),
('ZA', 'South Africa', 'ZAF', 'Africa', 'ZAR', '+27', '🇿🇦', FALSE),
('SS', 'South Sudan', 'SSD', 'Africa', 'SSP', '+211', '🇸🇸', FALSE),
('LK', 'Sri Lanka', 'LKA', 'Asia', 'LKR', '+94', '🇱🇰', FALSE),
('SD', 'Sudan', 'SDN', 'Africa', 'SDG', '+249', '🇸🇩', FALSE),
('SR', 'Suriname', 'SUR', 'South America', 'SRD', '+597', '🇸🇷', FALSE),
('SE', 'Sweden', 'SWE', 'Europe', 'SEK', '+46', '🇸🇪', FALSE),
('SY', 'Syria', 'SYR', 'Asia', 'SYP', '+963', '🇸🇾', FALSE),
('TW', 'Taiwan', 'TWN', 'Asia', 'TWD', '+886', '🇹🇼', FALSE),
('TJ', 'Tajikistan', 'TJK', 'Asia', 'TJS', '+992', '🇹🇯', FALSE),
('TZ', 'Tanzania', 'TZA', 'Africa', 'TZS', '+255', '🇹🇿', FALSE),
('TL', 'Timor-Leste', 'TLS', 'Asia', 'USD', '+670', '🇹🇱', FALSE),
('TG', 'Togo', 'TGO', 'Africa', 'XOF', '+228', '🇹🇬', FALSE),
('TO', 'Tonga', 'TON', 'Oceania', 'TOP', '+676', '🇹🇴', FALSE),
('TT', 'Trinidad and Tobago', 'TTO', 'North America', 'TTD', '+1868', '🇹🇹', FALSE),
('TN', 'Tunisia', 'TUN', 'Africa', 'TND', '+216', '🇹🇳', FALSE),
('TM', 'Turkmenistan', 'TKM', 'Asia', 'TMT', '+993', '🇹🇲', FALSE),
('TV', 'Tuvalu', 'TUV', 'Oceania', 'AUD', '+688', '🇹🇻', FALSE),
('UG', 'Uganda', 'UGA', 'Africa', 'UGX', '+256', '🇺🇬', FALSE),
('UA', 'Ukraine', 'UKR', 'Europe', 'UAH', '+380', '🇺🇦', FALSE),
('UY', 'Uruguay', 'URY', 'South America', 'UYU', '+598', '🇺🇾', FALSE),
('UZ', 'Uzbekistan', 'UZB', 'Asia', 'UZS', '+998', '🇺🇿', FALSE),
('VU', 'Vanuatu', 'VUT', 'Oceania', 'VUV', '+678', '🇻🇺', FALSE),
('VA', 'Vatican City', 'VAT', 'Europe', 'EUR', '+39', '🇻🇦', FALSE),
('VE', 'Venezuela', 'VEN', 'South America', 'VED', '+58', '🇻🇪', FALSE),
('VN', 'Vietnam', 'VNM', 'Asia', 'VND', '+84', '🇻🇳', FALSE),
('YE', 'Yemen', 'YEM', 'Asia', 'YER', '+967', '🇾🇪', FALSE),
('ZM', 'Zambia', 'ZMB', 'Africa', 'ZMW', '+260', '🇿🇲', FALSE),
('ZW', 'Zimbabwe', 'ZWE', 'Africa', 'ZWL', '+263', '🇿🇼', FALSE)

-- Handle conflicts by updating existing records
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    iso3_code = EXCLUDED.iso3_code,
    continent = EXCLUDED.continent,
    currency_code = EXCLUDED.currency_code,
    phone_prefix = EXCLUDED.phone_prefix,
    flag_emoji = EXCLUDED.flag_emoji,
    popular = EXCLUDED.popular,
    updated_at = CURRENT_TIMESTAMP;

-- Update any timestamp triggers
UPDATE countries SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;

-- Show completion message
DO $$
BEGIN
    RAISE NOTICE '✅ Successfully inserted/updated all 195 countries!';
    RAISE NOTICE '📊 Total countries in database: %', (SELECT COUNT(*) FROM countries);
    RAISE NOTICE '🌟 Popular travel destinations: %', (SELECT COUNT(*) FROM countries WHERE popular = TRUE);
END $$;
