-- ================================================
-- COMPREHENSIVE COUNTRIES SEED DATA (Updated for actual schema)
-- ================================================
-- Complete list of countries matching the existing table structure
-- Table structure: id (uuid), iso2, iso3, name, region_id, is_active, sort_order

-- Get the international region ID first
DO $$
DECLARE
    intl_region_id uuid;
    europe_region_id uuid;
    asia_region_id uuid;
    america_region_id uuid;
    africa_region_id uuid;
    oceania_region_id uuid;
BEGIN
    -- Get existing region IDs or create if needed
    SELECT id INTO intl_region_id FROM regions WHERE name = 'International' OR name = 'Europe' LIMIT 1;
    
    IF intl_region_id IS NULL THEN
        SELECT id INTO intl_region_id FROM regions LIMIT 1; -- Use any existing region as fallback
    END IF;
    
    -- Insert/update all countries with comprehensive list
    INSERT INTO countries (iso2, iso3, name, region_id, is_active, sort_order) VALUES
    -- Popular travel destinations (lower sort_order = higher priority)
    ('AE', 'ARE', 'United Arab Emirates', intl_region_id, TRUE, 5),
    ('US', 'USA', 'United States', intl_region_id, TRUE, 8),
    ('GB', 'GBR', 'United Kingdom', intl_region_id, TRUE, 10),
    ('FR', 'FRA', 'France', intl_region_id, TRUE, 12),
    ('ES', 'ESP', 'Spain', intl_region_id, TRUE, 15),
    ('IT', 'ITA', 'Italy', intl_region_id, TRUE, 18),
    ('DE', 'DEU', 'Germany', intl_region_id, TRUE, 20),
    ('IN', 'IND', 'India', intl_region_id, TRUE, 22),
    ('TH', 'THA', 'Thailand', intl_region_id, TRUE, 25),
    ('SG', 'SGP', 'Singapore', intl_region_id, TRUE, 28),
    ('JP', 'JPN', 'Japan', intl_region_id, TRUE, 30),
    ('AU', 'AUS', 'Australia', intl_region_id, TRUE, 32),
    ('GR', 'GRC', 'Greece', intl_region_id, TRUE, 35),
    ('TR', 'TUR', 'Turkey', intl_region_id, TRUE, 38),
    ('CH', 'CHE', 'Switzerland', intl_region_id, TRUE, 40),
    ('NL', 'NLD', 'Netherlands', intl_region_id, TRUE, 42),
    ('CA', 'CAN', 'Canada', intl_region_id, TRUE, 45),
    ('MY', 'MYS', 'Malaysia', intl_region_id, TRUE, 48),
    ('ID', 'IDN', 'Indonesia', intl_region_id, TRUE, 50),
    
    -- All other countries alphabetically (higher sort_order)
    ('AF', 'AFG', 'Afghanistan', intl_region_id, TRUE, 100),
    ('AL', 'ALB', 'Albania', intl_region_id, TRUE, 105),
    ('DZ', 'DZA', 'Algeria', intl_region_id, TRUE, 110),
    ('AD', 'AND', 'Andorra', intl_region_id, TRUE, 115),
    ('AO', 'AGO', 'Angola', intl_region_id, TRUE, 120),
    ('AG', 'ATG', 'Antigua and Barbuda', intl_region_id, TRUE, 125),
    ('AR', 'ARG', 'Argentina', intl_region_id, TRUE, 130),
    ('AM', 'ARM', 'Armenia', intl_region_id, TRUE, 135),
    ('AT', 'AUT', 'Austria', intl_region_id, TRUE, 140),
    ('AZ', 'AZE', 'Azerbaijan', intl_region_id, TRUE, 145),
    ('BS', 'BHS', 'Bahamas', intl_region_id, TRUE, 150),
    ('BH', 'BHR', 'Bahrain', intl_region_id, TRUE, 155),
    ('BD', 'BGD', 'Bangladesh', intl_region_id, TRUE, 160),
    ('BB', 'BRB', 'Barbados', intl_region_id, TRUE, 165),
    ('BY', 'BLR', 'Belarus', intl_region_id, TRUE, 170),
    ('BE', 'BEL', 'Belgium', intl_region_id, TRUE, 175),
    ('BZ', 'BLZ', 'Belize', intl_region_id, TRUE, 180),
    ('BJ', 'BEN', 'Benin', intl_region_id, TRUE, 185),
    ('BT', 'BTN', 'Bhutan', intl_region_id, TRUE, 190),
    ('BO', 'BOL', 'Bolivia', intl_region_id, TRUE, 195),
    ('BA', 'BIH', 'Bosnia and Herzegovina', intl_region_id, TRUE, 200),
    ('BW', 'BWA', 'Botswana', intl_region_id, TRUE, 205),
    ('BR', 'BRA', 'Brazil', intl_region_id, TRUE, 210),
    ('BN', 'BRN', 'Brunei', intl_region_id, TRUE, 215),
    ('BG', 'BGR', 'Bulgaria', intl_region_id, TRUE, 220),
    ('BF', 'BFA', 'Burkina Faso', intl_region_id, TRUE, 225),
    ('BI', 'BDI', 'Burundi', intl_region_id, TRUE, 230),
    ('CV', 'CPV', 'Cabo Verde', intl_region_id, TRUE, 235),
    ('KH', 'KHM', 'Cambodia', intl_region_id, TRUE, 240),
    ('CM', 'CMR', 'Cameroon', intl_region_id, TRUE, 245),
    ('CF', 'CAF', 'Central African Republic', intl_region_id, TRUE, 250),
    ('TD', 'TCD', 'Chad', intl_region_id, TRUE, 255),
    ('CL', 'CHL', 'Chile', intl_region_id, TRUE, 260),
    ('CN', 'CHN', 'China', intl_region_id, TRUE, 265),
    ('CO', 'COL', 'Colombia', intl_region_id, TRUE, 270),
    ('KM', 'COM', 'Comoros', intl_region_id, TRUE, 275),
    ('CG', 'COG', 'Congo', intl_region_id, TRUE, 280),
    ('CD', 'COD', 'Democratic Republic of the Congo', intl_region_id, TRUE, 285),
    ('CR', 'CRI', 'Costa Rica', intl_region_id, TRUE, 290),
    ('CI', 'CIV', 'Côte d''Ivoire', intl_region_id, TRUE, 295),
    ('HR', 'HRV', 'Croatia', intl_region_id, TRUE, 300),
    ('CU', 'CUB', 'Cuba', intl_region_id, TRUE, 305),
    ('CY', 'CYP', 'Cyprus', intl_region_id, TRUE, 310),
    ('CZ', 'CZE', 'Czech Republic', intl_region_id, TRUE, 315),
    ('DK', 'DNK', 'Denmark', intl_region_id, TRUE, 320),
    ('DJ', 'DJI', 'Djibouti', intl_region_id, TRUE, 325),
    ('DM', 'DMA', 'Dominica', intl_region_id, TRUE, 330),
    ('DO', 'DOM', 'Dominican Republic', intl_region_id, TRUE, 335),
    ('EC', 'ECU', 'Ecuador', intl_region_id, TRUE, 340),
    ('EG', 'EGY', 'Egypt', intl_region_id, TRUE, 345),
    ('SV', 'SLV', 'El Salvador', intl_region_id, TRUE, 350),
    ('GQ', 'GNQ', 'Equatorial Guinea', intl_region_id, TRUE, 355),
    ('ER', 'ERI', 'Eritrea', intl_region_id, TRUE, 360),
    ('EE', 'EST', 'Estonia', intl_region_id, TRUE, 365),
    ('SZ', 'SWZ', 'Eswatini', intl_region_id, TRUE, 370),
    ('ET', 'ETH', 'Ethiopia', intl_region_id, TRUE, 375),
    ('FJ', 'FJI', 'Fiji', intl_region_id, TRUE, 380),
    ('FI', 'FIN', 'Finland', intl_region_id, TRUE, 385),
    ('GA', 'GAB', 'Gabon', intl_region_id, TRUE, 390),
    ('GM', 'GMB', 'Gambia', intl_region_id, TRUE, 395),
    ('GE', 'GEO', 'Georgia', intl_region_id, TRUE, 400),
    ('GH', 'GHA', 'Ghana', intl_region_id, TRUE, 405),
    ('GD', 'GRD', 'Grenada', intl_region_id, TRUE, 410),
    ('GT', 'GTM', 'Guatemala', intl_region_id, TRUE, 415),
    ('GN', 'GIN', 'Guinea', intl_region_id, TRUE, 420),
    ('GW', 'GNB', 'Guinea-Bissau', intl_region_id, TRUE, 425),
    ('GY', 'GUY', 'Guyana', intl_region_id, TRUE, 430),
    ('HT', 'HTI', 'Haiti', intl_region_id, TRUE, 435),
    ('HN', 'HND', 'Honduras', intl_region_id, TRUE, 440),
    ('HU', 'HUN', 'Hungary', intl_region_id, TRUE, 445),
    ('IS', 'ISL', 'Iceland', intl_region_id, TRUE, 450),
    ('IR', 'IRN', 'Iran', intl_region_id, TRUE, 455),
    ('IQ', 'IRQ', 'Iraq', intl_region_id, TRUE, 460),
    ('IE', 'IRL', 'Ireland', intl_region_id, TRUE, 465),
    ('IL', 'ISR', 'Israel', intl_region_id, TRUE, 470),
    ('JM', 'JAM', 'Jamaica', intl_region_id, TRUE, 475),
    ('JO', 'JOR', 'Jordan', intl_region_id, TRUE, 480),
    ('KZ', 'KAZ', 'Kazakhstan', intl_region_id, TRUE, 485),
    ('KE', 'KEN', 'Kenya', intl_region_id, TRUE, 490),
    ('KI', 'KIR', 'Kiribati', intl_region_id, TRUE, 495),
    ('KP', 'PRK', 'North Korea', intl_region_id, TRUE, 500),
    ('KR', 'KOR', 'South Korea', intl_region_id, TRUE, 505),
    ('KW', 'KWT', 'Kuwait', intl_region_id, TRUE, 510),
    ('KG', 'KGZ', 'Kyrgyzstan', intl_region_id, TRUE, 515),
    ('LA', 'LAO', 'Laos', intl_region_id, TRUE, 520),
    ('LV', 'LVA', 'Latvia', intl_region_id, TRUE, 525),
    ('LB', 'LBN', 'Lebanon', intl_region_id, TRUE, 530),
    ('LS', 'LSO', 'Lesotho', intl_region_id, TRUE, 535),
    ('LR', 'LBR', 'Liberia', intl_region_id, TRUE, 540),
    ('LY', 'LBY', 'Libya', intl_region_id, TRUE, 545),
    ('LI', 'LIE', 'Liechtenstein', intl_region_id, TRUE, 550),
    ('LT', 'LTU', 'Lithuania', intl_region_id, TRUE, 555),
    ('LU', 'LUX', 'Luxembourg', intl_region_id, TRUE, 560),
    ('MG', 'MDG', 'Madagascar', intl_region_id, TRUE, 565),
    ('MW', 'MWI', 'Malawi', intl_region_id, TRUE, 570),
    ('MV', 'MDV', 'Maldives', intl_region_id, TRUE, 575),
    ('ML', 'MLI', 'Mali', intl_region_id, TRUE, 580),
    ('MT', 'MLT', 'Malta', intl_region_id, TRUE, 585),
    ('MH', 'MHL', 'Marshall Islands', intl_region_id, TRUE, 590),
    ('MR', 'MRT', 'Mauritania', intl_region_id, TRUE, 595),
    ('MU', 'MUS', 'Mauritius', intl_region_id, TRUE, 600),
    ('MX', 'MEX', 'Mexico', intl_region_id, TRUE, 605),
    ('FM', 'FSM', 'Micronesia', intl_region_id, TRUE, 610),
    ('MD', 'MDA', 'Moldova', intl_region_id, TRUE, 615),
    ('MC', 'MCO', 'Monaco', intl_region_id, TRUE, 620),
    ('MN', 'MNG', 'Mongolia', intl_region_id, TRUE, 625),
    ('ME', 'MNE', 'Montenegro', intl_region_id, TRUE, 630),
    ('MA', 'MAR', 'Morocco', intl_region_id, TRUE, 635),
    ('MZ', 'MOZ', 'Mozambique', intl_region_id, TRUE, 640),
    ('MM', 'MMR', 'Myanmar', intl_region_id, TRUE, 645),
    ('NA', 'NAM', 'Namibia', intl_region_id, TRUE, 650),
    ('NR', 'NRU', 'Nauru', intl_region_id, TRUE, 655),
    ('NP', 'NPL', 'Nepal', intl_region_id, TRUE, 660),
    ('NZ', 'NZL', 'New Zealand', intl_region_id, TRUE, 665),
    ('NI', 'NIC', 'Nicaragua', intl_region_id, TRUE, 670),
    ('NE', 'NER', 'Niger', intl_region_id, TRUE, 675),
    ('NG', 'NGA', 'Nigeria', intl_region_id, TRUE, 680),
    ('MK', 'MKD', 'North Macedonia', intl_region_id, TRUE, 685),
    ('NO', 'NOR', 'Norway', intl_region_id, TRUE, 690),
    ('OM', 'OMN', 'Oman', intl_region_id, TRUE, 695),
    ('PK', 'PAK', 'Pakistan', intl_region_id, TRUE, 700),
    ('PW', 'PLW', 'Palau', intl_region_id, TRUE, 705),
    ('PA', 'PAN', 'Panama', intl_region_id, TRUE, 710),
    ('PG', 'PNG', 'Papua New Guinea', intl_region_id, TRUE, 715),
    ('PY', 'PRY', 'Paraguay', intl_region_id, TRUE, 720),
    ('PE', 'PER', 'Peru', intl_region_id, TRUE, 725),
    ('PH', 'PHL', 'Philippines', intl_region_id, TRUE, 730),
    ('PL', 'POL', 'Poland', intl_region_id, TRUE, 735),
    ('PT', 'PRT', 'Portugal', intl_region_id, TRUE, 740),
    ('QA', 'QAT', 'Qatar', intl_region_id, TRUE, 745),
    ('RO', 'ROU', 'Romania', intl_region_id, TRUE, 750),
    ('RU', 'RUS', 'Russia', intl_region_id, TRUE, 755),
    ('RW', 'RWA', 'Rwanda', intl_region_id, TRUE, 760),
    ('KN', 'KNA', 'Saint Kitts and Nevis', intl_region_id, TRUE, 765),
    ('LC', 'LCA', 'Saint Lucia', intl_region_id, TRUE, 770),
    ('VC', 'VCT', 'Saint Vincent and the Grenadines', intl_region_id, TRUE, 775),
    ('WS', 'WSM', 'Samoa', intl_region_id, TRUE, 780),
    ('SM', 'SMR', 'San Marino', intl_region_id, TRUE, 785),
    ('ST', 'STP', 'São Tomé and Príncipe', intl_region_id, TRUE, 790),
    ('SA', 'SAU', 'Saudi Arabia', intl_region_id, TRUE, 795),
    ('SN', 'SEN', 'Senegal', intl_region_id, TRUE, 800),
    ('RS', 'SRB', 'Serbia', intl_region_id, TRUE, 805),
    ('SC', 'SYC', 'Seychelles', intl_region_id, TRUE, 810),
    ('SL', 'SLE', 'Sierra Leone', intl_region_id, TRUE, 815),
    ('SK', 'SVK', 'Slovakia', intl_region_id, TRUE, 820),
    ('SI', 'SVN', 'Slovenia', intl_region_id, TRUE, 825),
    ('SB', 'SLB', 'Solomon Islands', intl_region_id, TRUE, 830),
    ('SO', 'SOM', 'Somalia', intl_region_id, TRUE, 835),
    ('ZA', 'ZAF', 'South Africa', intl_region_id, TRUE, 840),
    ('SS', 'SSD', 'South Sudan', intl_region_id, TRUE, 845),
    ('LK', 'LKA', 'Sri Lanka', intl_region_id, TRUE, 850),
    ('SD', 'SDN', 'Sudan', intl_region_id, TRUE, 855),
    ('SR', 'SUR', 'Suriname', intl_region_id, TRUE, 860),
    ('SE', 'SWE', 'Sweden', intl_region_id, TRUE, 865),
    ('SY', 'SYR', 'Syria', intl_region_id, TRUE, 870),
    ('TW', 'TWN', 'Taiwan', intl_region_id, TRUE, 875),
    ('TJ', 'TJK', 'Tajikistan', intl_region_id, TRUE, 880),
    ('TZ', 'TZA', 'Tanzania', intl_region_id, TRUE, 885),
    ('TL', 'TLS', 'Timor-Leste', intl_region_id, TRUE, 890),
    ('TG', 'TGO', 'Togo', intl_region_id, TRUE, 895),
    ('TO', 'TON', 'Tonga', intl_region_id, TRUE, 900),
    ('TT', 'TTO', 'Trinidad and Tobago', intl_region_id, TRUE, 905),
    ('TN', 'TUN', 'Tunisia', intl_region_id, TRUE, 910),
    ('TM', 'TKM', 'Turkmenistan', intl_region_id, TRUE, 915),
    ('TV', 'TUV', 'Tuvalu', intl_region_id, TRUE, 920),
    ('UG', 'UGA', 'Uganda', intl_region_id, TRUE, 925),
    ('UA', 'UKR', 'Ukraine', intl_region_id, TRUE, 930),
    ('UY', 'URY', 'Uruguay', intl_region_id, TRUE, 935),
    ('UZ', 'UZB', 'Uzbekistan', intl_region_id, TRUE, 940),
    ('VU', 'VUT', 'Vanuatu', intl_region_id, TRUE, 945),
    ('VA', 'VAT', 'Vatican City', intl_region_id, TRUE, 950),
    ('VE', 'VEN', 'Venezuela', intl_region_id, TRUE, 955),
    ('VN', 'VNM', 'Vietnam', intl_region_id, TRUE, 960),
    ('YE', 'YEM', 'Yemen', intl_region_id, TRUE, 965),
    ('ZM', 'ZMB', 'Zambia', intl_region_id, TRUE, 970),
    ('ZW', 'ZWE', 'Zimbabwe', intl_region_id, TRUE, 975)

    -- Handle conflicts by updating existing records
    ON CONFLICT (iso2) DO UPDATE SET
        iso3 = EXCLUDED.iso3,
        name = EXCLUDED.name,
        region_id = EXCLUDED.region_id,
        is_active = EXCLUDED.is_active,
        sort_order = EXCLUDED.sort_order,
        updated_at = now();
    
    -- Show completion message
    RAISE NOTICE '✅ Successfully inserted/updated comprehensive countries list!';
    RAISE NOTICE '📊 Total countries in database: %', (SELECT COUNT(*) FROM countries);
    RAISE NOTICE '🌟 Popular destinations (sort_order < 100): %', (SELECT COUNT(*) FROM countries WHERE sort_order < 100);
END $$;
