[build]
  command = "npm install --include=dev --save-dev && npm run build:client"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirect /auth/* → Render backend
[[redirects]]
  from = "/auth/*"
  to = "https://builder-faredown-pricing.onrender.com/auth/:splat"
  status = 200
  force = true

# Redirect /api/* → Render backend
[[redirects]]
  from = "/api/*"
  to = "https://builder-faredown-pricing.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback (must always be LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
