[build]
  command = "npm ci && npm run build:client"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# Redirect /auth/* → Render backend
[[redirects]]
  from = "/auth/*"
  to = "https://builder-faredown-pricing.onrender.com/auth/:splat"
  status = 200
  force = true

# Redirect /api/* → Render backend
[[redirects]]
  from = "/api/*"
  to = "https://builder-faredown-pricing.onrender.com/api/:splat"
  status = 200
  force = true

# Netlify health endpoint
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

# SPA fallback (must always be LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
