services:
  # Faredown Backend API
  - type: web
    name: faredown-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    plan: free
    envVars:
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: faredown-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: "https://55e69d5755db4519a9295a29a1a55930-aaf2790235d34f3ab48afa56a.fly.dev,https://faredown.com,https://www.faredown.com"
      - key: AMADEUS_API_KEY
        value: "demo_key"
      - key: BOOKING_COM_API_KEY
        value: "demo_key"
      - key: OPENAI_API_KEY
        value: "demo_key"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: EXCHANGE_RATE_API_KEY
        value: "demo_key"
      - key: LOG_LEVEL
        value: "INFO"

  # PostgreSQL Database
databases:
  - name: faredown-db
    plan: free
    databaseName: faredown
    user: faredown_user
