-- ================================================
-- SIMPLE COUNTRIES INSERT (No conflict resolution)
-- ================================================
-- Insert countries that don't already exist

DO $$
DECLARE
    region_id_to_use uuid;
    inserted_count integer := 0;
BEGIN
    -- Get any existing region ID to use
    SELECT id INTO region_id_to_use FROM regions LIMIT 1;
    
    IF region_id_to_use IS NULL THEN
        RAISE EXCEPTION 'No regions found in database. Please create regions first.';
    END IF;
    
    RAISE NOTICE 'Using region ID: %', region_id_to_use;
    
    -- Popular countries (if they don't exist)
    INSERT INTO countries (iso2, iso3, name, region_id, is_active, sort_order)
    SELECT * FROM (VALUES
        ('AE', 'ARE', 'United Arab Emirates', region_id_to_use, TRUE, 5),
        ('US', 'USA', 'United States', region_id_to_use, TRUE, 8),
        ('CA', 'CAN', 'Canada', region_id_to_use, TRUE, 10),
        ('SG', 'SGP', 'Singapore', region_id_to_use, TRUE, 15),
        ('JP', 'JPN', 'Japan', region_id_to_use, TRUE, 20),
        ('AU', 'AUS', 'Australia', region_id_to_use, TRUE, 25),
        ('NZ', 'NZL', 'New Zealand', region_id_to_use, TRUE, 30),
        ('TH', 'THA', 'Thailand', region_id_to_use, TRUE, 35),
        ('MY', 'MYS', 'Malaysia', region_id_to_use, TRUE, 40),
        ('ID', 'IDN', 'Indonesia', region_id_to_use, TRUE, 45),
        ('PH', 'PHL', 'Philippines', region_id_to_use, TRUE, 50),
        ('VN', 'VNM', 'Vietnam', region_id_to_use, TRUE, 55),
        ('KR', 'KOR', 'South Korea', region_id_to_use, TRUE, 60),
        ('CN', 'CHN', 'China', region_id_to_use, TRUE, 65),
        ('HK', 'HKG', 'Hong Kong', region_id_to_use, TRUE, 70),
        ('TW', 'TWN', 'Taiwan', region_id_to_use, TRUE, 75),
        ('MX', 'MEX', 'Mexico', region_id_to_use, TRUE, 80),
        ('BR', 'BRA', 'Brazil', region_id_to_use, TRUE, 85),
        ('AR', 'ARG', 'Argentina', region_id_to_use, TRUE, 90),
        ('CL', 'CHL', 'Chile', region_id_to_use, TRUE, 95),
        
        -- African countries
        ('ZA', 'ZAF', 'South Africa', region_id_to_use, TRUE, 200),
        ('EG', 'EGY', 'Egypt', region_id_to_use, TRUE, 205),
        ('MA', 'MAR', 'Morocco', region_id_to_use, TRUE, 210),
        ('KE', 'KEN', 'Kenya', region_id_to_use, TRUE, 215),
        ('TZ', 'TZA', 'Tanzania', region_id_to_use, TRUE, 220),
        ('GH', 'GHA', 'Ghana', region_id_to_use, TRUE, 225),
        ('NG', 'NGA', 'Nigeria', region_id_to_use, TRUE, 230),
        ('ET', 'ETH', 'Ethiopia', region_id_to_use, TRUE, 235),
        ('RW', 'RWA', 'Rwanda', region_id_to_use, TRUE, 240),
        ('UG', 'UGA', 'Uganda', region_id_to_use, TRUE, 245),
        
        -- Middle East
        ('SA', 'SAU', 'Saudi Arabia', region_id_to_use, TRUE, 300),
        ('QA', 'QAT', 'Qatar', region_id_to_use, TRUE, 305),
        ('KW', 'KWT', 'Kuwait', region_id_to_use, TRUE, 310),
        ('BH', 'BHR', 'Bahrain', region_id_to_use, TRUE, 315),
        ('OM', 'OMN', 'Oman', region_id_to_use, TRUE, 320),
        ('IL', 'ISR', 'Israel', region_id_to_use, TRUE, 325),
        ('JO', 'JOR', 'Jordan', region_id_to_use, TRUE, 330),
        ('LB', 'LBN', 'Lebanon', region_id_to_use, TRUE, 335),
        
        -- Rest of world
        ('AF', 'AFG', 'Afghanistan', region_id_to_use, TRUE, 500),
        ('AL', 'ALB', 'Albania', region_id_to_use, TRUE, 505),
        ('DZ', 'DZA', 'Algeria', region_id_to_use, TRUE, 510),
        ('AD', 'AND', 'Andorra', region_id_to_use, TRUE, 515),
        ('AO', 'AGO', 'Angola', region_id_to_use, TRUE, 520),
        ('AG', 'ATG', 'Antigua and Barbuda', region_id_to_use, TRUE, 525),
        ('AM', 'ARM', 'Armenia', region_id_to_use, TRUE, 530),
        ('AT', 'AUT', 'Austria', region_id_to_use, TRUE, 535),
        ('AZ', 'AZE', 'Azerbaijan', region_id_to_use, TRUE, 540),
        ('BS', 'BHS', 'Bahamas', region_id_to_use, TRUE, 545),
        ('BD', 'BGD', 'Bangladesh', region_id_to_use, TRUE, 550),
        ('BB', 'BRB', 'Barbados', region_id_to_use, TRUE, 555),
        ('BY', 'BLR', 'Belarus', region_id_to_use, TRUE, 560),
        ('BE', 'BEL', 'Belgium', region_id_to_use, TRUE, 565),
        ('BZ', 'BLZ', 'Belize', region_id_to_use, TRUE, 570),
        ('BJ', 'BEN', 'Benin', region_id_to_use, TRUE, 575),
        ('BT', 'BTN', 'Bhutan', region_id_to_use, TRUE, 580),
        ('BO', 'BOL', 'Bolivia', region_id_to_use, TRUE, 585),
        ('BA', 'BIH', 'Bosnia and Herzegovina', region_id_to_use, TRUE, 590),
        ('BW', 'BWA', 'Botswana', region_id_to_use, TRUE, 595),
        ('BN', 'BRN', 'Brunei', region_id_to_use, TRUE, 600),
        ('BG', 'BGR', 'Bulgaria', region_id_to_use, TRUE, 605),
        ('BF', 'BFA', 'Burkina Faso', region_id_to_use, TRUE, 610),
        ('BI', 'BDI', 'Burundi', region_id_to_use, TRUE, 615),
        ('CV', 'CPV', 'Cabo Verde', region_id_to_use, TRUE, 620),
        ('KH', 'KHM', 'Cambodia', region_id_to_use, TRUE, 625),
        ('CM', 'CMR', 'Cameroon', region_id_to_use, TRUE, 630),
        ('CF', 'CAF', 'Central African Republic', region_id_to_use, TRUE, 635),
        ('TD', 'TCD', 'Chad', region_id_to_use, TRUE, 640),
        ('CO', 'COL', 'Colombia', region_id_to_use, TRUE, 645),
        ('KM', 'COM', 'Comoros', region_id_to_use, TRUE, 650),
        ('CG', 'COG', 'Congo', region_id_to_use, TRUE, 655),
        ('CD', 'COD', 'Democratic Republic of the Congo', region_id_to_use, TRUE, 660),
        ('CR', 'CRI', 'Costa Rica', region_id_to_use, TRUE, 665),
        ('CI', 'CIV', 'Côte d''Ivoire', region_id_to_use, TRUE, 670),
        ('HR', 'HRV', 'Croatia', region_id_to_use, TRUE, 675),
        ('CU', 'CUB', 'Cuba', region_id_to_use, TRUE, 680),
        ('CY', 'CYP', 'Cyprus', region_id_to_use, TRUE, 685),
        ('CZ', 'CZE', 'Czech Republic', region_id_to_use, TRUE, 690),
        ('DK', 'DNK', 'Denmark', region_id_to_use, TRUE, 695),
        ('DJ', 'DJI', 'Djibouti', region_id_to_use, TRUE, 700),
        ('DM', 'DMA', 'Dominica', region_id_to_use, TRUE, 705),
        ('DO', 'DOM', 'Dominican Republic', region_id_to_use, TRUE, 710),
        ('EC', 'ECU', 'Ecuador', region_id_to_use, TRUE, 715),
        ('SV', 'SLV', 'El Salvador', region_id_to_use, TRUE, 720),
        ('GQ', 'GNQ', 'Equatorial Guinea', region_id_to_use, TRUE, 725),
        ('ER', 'ERI', 'Eritrea', region_id_to_use, TRUE, 730),
        ('EE', 'EST', 'Estonia', region_id_to_use, TRUE, 735),
        ('SZ', 'SWZ', 'Eswatini', region_id_to_use, TRUE, 740),
        ('FJ', 'FJI', 'Fiji', region_id_to_use, TRUE, 745),
        ('FI', 'FIN', 'Finland', region_id_to_use, TRUE, 750),
        ('GA', 'GAB', 'Gabon', region_id_to_use, TRUE, 755),
        ('GM', 'GMB', 'Gambia', region_id_to_use, TRUE, 760),
        ('GE', 'GEO', 'Georgia', region_id_to_use, TRUE, 765),
        ('GD', 'GRD', 'Grenada', region_id_to_use, TRUE, 770),
        ('GT', 'GTM', 'Guatemala', region_id_to_use, TRUE, 775),
        ('GN', 'GIN', 'Guinea', region_id_to_use, TRUE, 780),
        ('GW', 'GNB', 'Guinea-Bissau', region_id_to_use, TRUE, 785),
        ('GY', 'GUY', 'Guyana', region_id_to_use, TRUE, 790),
        ('HT', 'HTI', 'Haiti', region_id_to_use, TRUE, 795),
        ('HN', 'HND', 'Honduras', region_id_to_use, TRUE, 800),
        ('HU', 'HUN', 'Hungary', region_id_to_use, TRUE, 805),
        ('IS', 'ISL', 'Iceland', region_id_to_use, TRUE, 810),
        ('IN', 'IND', 'India', region_id_to_use, TRUE, 815),
        ('IR', 'IRN', 'Iran', region_id_to_use, TRUE, 820),
        ('IQ', 'IRQ', 'Iraq', region_id_to_use, TRUE, 825),
        ('IE', 'IRL', 'Ireland', region_id_to_use, TRUE, 830),
        ('JM', 'JAM', 'Jamaica', region_id_to_use, TRUE, 835),
        ('KZ', 'KAZ', 'Kazakhstan', region_id_to_use, TRUE, 840),
        ('KI', 'KIR', 'Kiribati', region_id_to_use, TRUE, 845),
        ('KP', 'PRK', 'North Korea', region_id_to_use, TRUE, 850),
        ('KG', 'KGZ', 'Kyrgyzstan', region_id_to_use, TRUE, 855),
        ('LA', 'LAO', 'Laos', region_id_to_use, TRUE, 860),
        ('LV', 'LVA', 'Latvia', region_id_to_use, TRUE, 865),
        ('LS', 'LSO', 'Lesotho', region_id_to_use, TRUE, 870),
        ('LR', 'LBR', 'Liberia', region_id_to_use, TRUE, 875),
        ('LY', 'LBY', 'Libya', region_id_to_use, TRUE, 880),
        ('LI', 'LIE', 'Liechtenstein', region_id_to_use, TRUE, 885),
        ('LT', 'LTU', 'Lithuania', region_id_to_use, TRUE, 890),
        ('LU', 'LUX', 'Luxembourg', region_id_to_use, TRUE, 895),
        ('MG', 'MDG', 'Madagascar', region_id_to_use, TRUE, 900),
        ('MW', 'MWI', 'Malawi', region_id_to_use, TRUE, 905),
        ('MV', 'MDV', 'Maldives', region_id_to_use, TRUE, 910),
        ('ML', 'MLI', 'Mali', region_id_to_use, TRUE, 915),
        ('MT', 'MLT', 'Malta', region_id_to_use, TRUE, 920),
        ('MH', 'MHL', 'Marshall Islands', region_id_to_use, TRUE, 925),
        ('MR', 'MRT', 'Mauritania', region_id_to_use, TRUE, 930),
        ('MU', 'MUS', 'Mauritius', region_id_to_use, TRUE, 935),
        ('FM', 'FSM', 'Micronesia', region_id_to_use, TRUE, 940),
        ('MD', 'MDA', 'Moldova', region_id_to_use, TRUE, 945),
        ('MC', 'MCO', 'Monaco', region_id_to_use, TRUE, 950),
        ('MN', 'MNG', 'Mongolia', region_id_to_use, TRUE, 955),
        ('ME', 'MNE', 'Montenegro', region_id_to_use, TRUE, 960),
        ('MZ', 'MOZ', 'Mozambique', region_id_to_use, TRUE, 965),
        ('MM', 'MMR', 'Myanmar', region_id_to_use, TRUE, 970),
        ('NA', 'NAM', 'Namibia', region_id_to_use, TRUE, 975),
        ('NR', 'NRU', 'Nauru', region_id_to_use, TRUE, 980),
        ('NP', 'NPL', 'Nepal', region_id_to_use, TRUE, 985),
        ('NI', 'NIC', 'Nicaragua', region_id_to_use, TRUE, 990),
        ('NE', 'NER', 'Niger', region_id_to_use, TRUE, 995),
        ('MK', 'MKD', 'North Macedonia', region_id_to_use, TRUE, 1000),
        ('NO', 'NOR', 'Norway', region_id_to_use, TRUE, 1005),
        ('PK', 'PAK', 'Pakistan', region_id_to_use, TRUE, 1010),
        ('PW', 'PLW', 'Palau', region_id_to_use, TRUE, 1015),
        ('PA', 'PAN', 'Panama', region_id_to_use, TRUE, 1020),
        ('PG', 'PNG', 'Papua New Guinea', region_id_to_use, TRUE, 1025),
        ('PY', 'PRY', 'Paraguay', region_id_to_use, TRUE, 1030),
        ('PE', 'PER', 'Peru', region_id_to_use, TRUE, 1035),
        ('PL', 'POL', 'Poland', region_id_to_use, TRUE, 1040),
        ('PT', 'PRT', 'Portugal', region_id_to_use, TRUE, 1045),
        ('RO', 'ROU', 'Romania', region_id_to_use, TRUE, 1050),
        ('RU', 'RUS', 'Russia', region_id_to_use, TRUE, 1055),
        ('KN', 'KNA', 'Saint Kitts and Nevis', region_id_to_use, TRUE, 1060),
        ('LC', 'LCA', 'Saint Lucia', region_id_to_use, TRUE, 1065),
        ('VC', 'VCT', 'Saint Vincent and the Grenadines', region_id_to_use, TRUE, 1070),
        ('WS', 'WSM', 'Samoa', region_id_to_use, TRUE, 1075),
        ('SM', 'SMR', 'San Marino', region_id_to_use, TRUE, 1080),
        ('ST', 'STP', 'São Tomé and Príncipe', region_id_to_use, TRUE, 1085),
        ('SN', 'SEN', 'Senegal', region_id_to_use, TRUE, 1090),
        ('RS', 'SRB', 'Serbia', region_id_to_use, TRUE, 1095),
        ('SC', 'SYC', 'Seychelles', region_id_to_use, TRUE, 1100),
        ('SL', 'SLE', 'Sierra Leone', region_id_to_use, TRUE, 1105),
        ('SK', 'SVK', 'Slovakia', region_id_to_use, TRUE, 1110),
        ('SI', 'SVN', 'Slovenia', region_id_to_use, TRUE, 1115),
        ('SB', 'SLB', 'Solomon Islands', region_id_to_use, TRUE, 1120),
        ('SO', 'SOM', 'Somalia', region_id_to_use, TRUE, 1125),
        ('SS', 'SSD', 'South Sudan', region_id_to_use, TRUE, 1130),
        ('LK', 'LKA', 'Sri Lanka', region_id_to_use, TRUE, 1135),
        ('SD', 'SDN', 'Sudan', region_id_to_use, TRUE, 1140),
        ('SR', 'SUR', 'Suriname', region_id_to_use, TRUE, 1145),
        ('SE', 'SWE', 'Sweden', region_id_to_use, TRUE, 1150),
        ('SY', 'SYR', 'Syria', region_id_to_use, TRUE, 1155),
        ('TJ', 'TJK', 'Tajikistan', region_id_to_use, TRUE, 1160),
        ('TL', 'TLS', 'Timor-Leste', region_id_to_use, TRUE, 1165),
        ('TG', 'TGO', 'Togo', region_id_to_use, TRUE, 1170),
        ('TO', 'TON', 'Tonga', region_id_to_use, TRUE, 1175),
        ('TT', 'TTO', 'Trinidad and Tobago', region_id_to_use, TRUE, 1180),
        ('TN', 'TUN', 'Tunisia', region_id_to_use, TRUE, 1185),
        ('TM', 'TKM', 'Turkmenistan', region_id_to_use, TRUE, 1190),
        ('TV', 'TUV', 'Tuvalu', region_id_to_use, TRUE, 1195),
        ('UA', 'UKR', 'Ukraine', region_id_to_use, TRUE, 1200),
        ('UY', 'URY', 'Uruguay', region_id_to_use, TRUE, 1205),
        ('UZ', 'UZB', 'Uzbekistan', region_id_to_use, TRUE, 1210),
        ('VU', 'VUT', 'Vanuatu', region_id_to_use, TRUE, 1215),
        ('VA', 'VAT', 'Vatican City', region_id_to_use, TRUE, 1220),
        ('VE', 'VEN', 'Venezuela', region_id_to_use, TRUE, 1225),
        ('YE', 'YEM', 'Yemen', region_id_to_use, TRUE, 1230),
        ('ZM', 'ZMB', 'Zambia', region_id_to_use, TRUE, 1235),
        ('ZW', 'ZWE', 'Zimbabwe', region_id_to_use, TRUE, 1240)
    ) AS new_countries(iso2, iso3, name, region_id, is_active, sort_order)
    WHERE NOT EXISTS (
        SELECT 1 FROM countries WHERE countries.iso2 = new_countries.iso2
    );
    
    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    
    RAISE NOTICE '✅ Successfully inserted % new countries!', inserted_count;
    RAISE NOTICE '📊 Total countries in database: %', (SELECT COUNT(*) FROM countries);
    RAISE NOTICE '🌟 Popular countries (sort_order < 100): %', (SELECT COUNT(*) FROM countries WHERE sort_order < 100);
END $$;
