-- ========================================
-- Faredown Country Master Seed - Full 249
-- ========================================

-- Create the countries table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.countries (
    id SERIAL PRIMARY KEY,
    iso2 CHAR(2) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    iso3_code CHAR(3),
    continent VARCHAR(50),
    currency_code CHAR(3),
    phone_prefix VARCHAR(15),
    flag_emoji VARCHAR(10),
    popular BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Clear existing data and reset sequence
TRUNCATE TABLE public.countries RESTART IDENTITY;

-- Insert all 249 countries with full data
INSERT INTO public.countries (iso2, name, iso3_code, continent, currency_code, phone_prefix, flag_emoji, popular) VALUES
('AD', 'Andorra', 'AND', 'Europe', 'EUR', '+376', '🇦🇩', false),
('AE', 'United Arab Emirates', 'ARE', 'Asia', 'AED', '+971', '🇦🇪', true),
('AF', 'Afghanistan', 'AFG', 'Asia', 'AFN', '+93', '🇦🇫', false),
('AG', 'Antigua and Barbuda', 'ATG', 'North America', 'XCD', '+1-268', '🇦🇬', false),
('AI', 'Anguilla', 'AIA', 'North America', 'XCD', '+1-264', '🇦🇮', false),
('AL', 'Albania', 'ALB', 'Europe', 'ALL', '+355', '🇦🇱', false),
('AM', 'Armenia', 'ARM', 'Asia', 'AMD', '+374', '🇦🇲', false),
('AO', 'Angola', 'AGO', 'Africa', 'AOA', '+244', '🇦🇴', false),
('AQ', 'Antarctica', 'ATA', 'Antarctica', NULL, NULL, '🇦🇶', false),
('AR', 'Argentina', 'ARG', 'South America', 'ARS', '+54', '🇦🇷', false),
('AS', 'American Samoa', 'ASM', 'Oceania', 'USD', '+1-684', '🇦🇸', false),
('AT', 'Austria', 'AUT', 'Europe', 'EUR', '+43', '🇦🇹', false),
('AU', 'Australia', 'AUS', 'Oceania', 'AUD', '+61', '🇦🇺', false),
('AW', 'Aruba', 'ABW', 'North America', 'AWG', '+297', '🇦🇼', false),
('AX', 'Åland Islands', 'ALA', 'Europe', 'EUR', '+358', '🇦🇽', false),
('AZ', 'Azerbaijan', 'AZE', 'Asia', 'AZN', '+994', '🇦🇿', false),
('BA', 'Bosnia and Herzegovina', 'BIH', 'Europe', 'BAM', '+387', '🇧🇦', false),
('BB', 'Barbados', 'BRB', 'North America', 'BBD', '+1-246', '🇧🇧', false),
('BD', 'Bangladesh', 'BGD', 'Asia', 'BDT', '+880', '🇧🇩', false),
('BE', 'Belgium', 'BEL', 'Europe', 'EUR', '+32', '🇧🇪', false),
('BF', 'Burkina Faso', 'BFA', 'Africa', 'XOF', '+226', '🇧🇫', false),
('BG', 'Bulgaria', 'BGR', 'Europe', 'BGN', '+359', '🇧🇬', false),
('BH', 'Bahrain', 'BHR', 'Asia', 'BHD', '+973', '🇧🇭', false),
('BI', 'Burundi', 'BDI', 'Africa', 'BIF', '+257', '🇧🇮', false),
('BJ', 'Benin', 'BEN', 'Africa', 'XOF', '+229', '🇧🇯', false),
('BL', 'Saint Barthélemy', 'BLM', 'North America', 'EUR', '+590', '🇧🇱', false),
('BM', 'Bermuda', 'BMU', 'North America', 'BMD', '+1-441', '🇧🇲', false),
('BN', 'Brunei Darussalam', 'BRN', 'Asia', 'BND', '+673', '🇧🇳', false),
('BO', 'Bolivia', 'BOL', 'South America', 'BOB', '+591', '🇧🇴', false),
('BQ', 'Bonaire, Sint Eustatius and Saba', 'BES', 'North America', 'USD', '+599', '🇧🇶', false),
('BR', 'Brazil', 'BRA', 'South America', 'BRL', '+55', '🇧🇷', false),
('BS', 'Bahamas', 'BHS', 'North America', 'BSD', '+1-242', '🇧🇸', false),
('BT', 'Bhutan', 'BTN', 'Asia', 'BTN', '+975', '🇧🇹', false),
('BV', 'Bouvet Island', 'BVT', 'Antarctica', 'NOK', NULL, '���🇻', false),
('BW', 'Botswana', 'BWA', 'Africa', 'BWP', '+267', '🇧🇼', false),
('BY', 'Belarus', 'BLR', 'Europe', 'BYN', '+375', '🇧🇾', false),
('BZ', 'Belize', 'BLZ', 'North America', 'BZD', '+501', '🇧🇿', false),
('CA', 'Canada', 'CAN', 'North America', 'CAD', '+1', '🇨🇦', false),
('CC', 'Cocos (Keeling) Islands', 'CCK', 'Oceania', 'AUD', '+61', '🇨🇨', false),
('CD', 'Congo, Democratic Republic of the', 'COD', 'Africa', 'CDF', '+243', '🇨🇩', false),
('CF', 'Central African Republic', 'CAF', 'Africa', 'XAF', '+236', '🇨🇫', false),
('CG', 'Congo', 'COG', 'Africa', 'XAF', '+242', '🇨🇬', false),
('CH', 'Switzerland', 'CHE', 'Europe', 'CHF', '+41', '🇨🇭', false),
('CI', 'Côte d''Ivoire', 'CIV', 'Africa', 'XOF', '+225', '🇨🇮', false),
('CK', 'Cook Islands', 'COK', 'Oceania', 'NZD', '+682', '🇨🇰', false),
('CL', 'Chile', 'CHL', 'South America', 'CLP', '+56', '🇨🇱', false),
('CM', 'Cameroon', 'CMR', 'Africa', 'XAF', '+237', '🇨🇲', false),
('CN', 'China', 'CHN', 'Asia', 'CNY', '+86', '🇨🇳', false),
('CO', 'Colombia', 'COL', 'South America', 'COP', '+57', '🇨🇴', false),
('CR', 'Costa Rica', 'CRI', 'North America', 'CRC', '+506', '🇨🇷', false),
('CU', 'Cuba', 'CUB', 'North America', 'CUP', '+53', '🇨🇺', false),
('CV', 'Cape Verde', 'CPV', 'Africa', 'CVE', '+238', '🇨🇻', false),
('CW', 'Curaçao', 'CUW', 'North America', 'ANG', '+599', '🇨🇼', false),
('CX', 'Christmas Island', 'CXR', 'Oceania', 'AUD', '+61', '🇨🇽', false),
('CY', 'Cyprus', 'CYP', 'Asia', 'EUR', '+357', '🇨🇾', false),
('CZ', 'Czech Republic', 'CZE', 'Europe', 'CZK', '+420', '🇨🇿', false),
('DE', 'Germany', 'DEU', 'Europe', 'EUR', '+49', '🇩🇪', false),
('DJ', 'Djibouti', 'DJI', 'Africa', 'DJF', '+253', '🇩🇯', false),
('DK', 'Denmark', 'DNK', 'Europe', 'DKK', '+45', '🇩🇰', false),
('DM', 'Dominica', 'DMA', 'North America', 'XCD', '+1-767', '🇩🇲', false),
('DO', 'Dominican Republic', 'DOM', 'North America', 'DOP', '+1-809', '🇩🇴', false),
('DZ', 'Algeria', 'DZA', 'Africa', 'DZD', '+213', '🇩🇿', false),
('EC', 'Ecuador', 'ECU', 'South America', 'USD', '+593', '🇪🇨', false),
('EE', 'Estonia', 'EST', 'Europe', 'EUR', '+372', '🇪🇪', false),
('EG', 'Egypt', 'EGY', 'Africa', 'EGP', '+20', '🇪🇬', false),
('EH', 'Western Sahara', 'ESH', 'Africa', 'MAD', '+212', '🇪🇭', false),
('ER', 'Eritrea', 'ERI', 'Africa', 'ERN', '+291', '🇪🇷', false),
('ES', 'Spain', 'ESP', 'Europe', 'EUR', '+34', '🇪🇸', false),
('ET', 'Ethiopia', 'ETH', 'Africa', 'ETB', '+251', '🇪🇹', false),
('FI', 'Finland', 'FIN', 'Europe', 'EUR', '+358', '🇫🇮', false),
('FJ', 'Fiji', 'FJI', 'Oceania', 'FJD', '+679', '🇫🇯', false),
('FK', 'Falkland Islands (Malvinas)', 'FLK', 'South America', 'FKP', '+500', '🇫🇰', false),
('FM', 'Micronesia, Federated States of', 'FSM', 'Oceania', 'USD', '+691', '🇫🇲', false),
('FO', 'Faroe Islands', 'FRO', 'Europe', 'DKK', '+298', '🇫🇴', false),
('FR', 'France', 'FRA', 'Europe', 'EUR', '+33', '🇫🇷', false),
('GA', 'Gabon', 'GAB', 'Africa', 'XAF', '+241', '🇬🇦', false),
('GB', 'United Kingdom', 'GBR', 'Europe', 'GBP', '+44', '🇬🇧', true),
('GD', 'Grenada', 'GRD', 'North America', 'XCD', '+1-473', '🇬🇩', false),
('GE', 'Georgia', 'GEO', 'Asia', 'GEL', '+995', '🇬🇪', false),
('GF', 'French Guiana', 'GUF', 'South America', 'EUR', '+594', '🇬🇫', false),
('GG', 'Guernsey', 'GGY', 'Europe', 'GBP', '+44', '🇬🇬', false),
('GH', 'Ghana', 'GHA', 'Africa', 'GHS', '+233', '🇬🇭', false),
('GI', 'Gibraltar', 'GIB', 'Europe', 'GIP', '+350', '🇬🇮', false),
('GL', 'Greenland', 'GRL', 'North America', 'DKK', '+299', '🇬🇱', false),
('GM', 'Gambia', 'GMB', 'Africa', 'GMD', '+220', '🇬🇲', false),
('GN', 'Guinea', 'GIN', 'Africa', 'GNF', '+224', '🇬🇳', false),
('GP', 'Guadeloupe', 'GLP', 'North America', 'EUR', '+590', '🇬🇵', false),
('GQ', 'Equatorial Guinea', 'GNQ', 'Africa', 'XAF', '+240', '🇬🇶', false),
('GR', 'Greece', 'GRC', 'Europe', 'EUR', '+30', '🇬🇷', false),
('GS', 'South Georgia and the South Sandwich Islands', 'SGS', 'Antarctica', 'GBP', NULL, '🇬🇸', false),
('GT', 'Guatemala', 'GTM', 'North America', 'GTQ', '+502', '🇬🇹', false),
('GU', 'Guam', 'GUM', 'Oceania', 'USD', '+1-671', '🇬🇺', false),
('GW', 'Guinea-Bissau', 'GNB', 'Africa', 'XOF', '+245', '🇬🇼', false),
('GY', 'Guyana', 'GUY', 'South America', 'GYD', '+592', '🇬🇾', false),
('HK', 'Hong Kong', 'HKG', 'Asia', 'HKD', '+852', '🇭🇰', false),
('HM', 'Heard Island and McDonald Islands', 'HMD', 'Antarctica', 'AUD', NULL, '🇭🇲', false),
('HN', 'Honduras', 'HND', 'North America', 'HNL', '+504', '🇭🇳', false),
('HR', 'Croatia', 'HRV', 'Europe', 'EUR', '+385', '🇭🇷', false),
('HT', 'Haiti', 'HTI', 'North America', 'HTG', '+509', '🇭🇹', false),
('HU', 'Hungary', 'HUN', 'Europe', 'HUF', '+36', '🇭🇺', false),
('ID', 'Indonesia', 'IDN', 'Asia', 'IDR', '+62', '🇮���', false),
('IE', 'Ireland', 'IRL', 'Europe', 'EUR', '+353', '🇮🇪', false),
('IL', 'Israel', 'ISR', 'Asia', 'ILS', '+972', '🇮🇱', false),
('IM', 'Isle of Man', 'IMN', 'Europe', 'GBP', '+44', '🇮🇲', false),
('IN', 'India', 'IND', 'Asia', 'INR', '+91', '🇮🇳', true),
('IO', 'British Indian Ocean Territory', 'IOT', 'Africa', 'USD', '+246', '🇮🇴', false),
('IQ', 'Iraq', 'IRQ', 'Asia', 'IQD', '+964', '🇮🇶', false),
('IR', 'Iran, Islamic Republic of', 'IRN', 'Asia', 'IRR', '+98', '🇮🇷', false),
('IS', 'Iceland', 'ISL', 'Europe', 'ISK', '+354', '🇮🇸', false),
('IT', 'Italy', 'ITA', 'Europe', 'EUR', '+39', '🇮🇹', false),
('JE', 'Jersey', 'JEY', 'Europe', 'GBP', '+44', '🇯🇪', false),
('JM', 'Jamaica', 'JAM', 'North America', 'JMD', '+1-876', '🇯🇲', false),
('JO', 'Jordan', 'JOR', 'Asia', 'JOD', '+962', '🇯🇴', false),
('JP', 'Japan', 'JPN', 'Asia', 'JPY', '+81', '🇯🇵', false),
('KE', 'Kenya', 'KEN', 'Africa', 'KES', '+254', '🇰🇪', false),
('KG', 'Kyrgyzstan', 'KGZ', 'Asia', 'KGS', '+996', '🇰🇬', false),
('KH', 'Cambodia', 'KHM', 'Asia', 'KHR', '+855', '🇰🇭', false),
('KI', 'Kiribati', 'KIR', 'Oceania', 'AUD', '+686', '🇰🇮', false),
('KM', 'Comoros', 'COM', 'Africa', 'KMF', '+269', '🇰🇲', false),
('KN', 'Saint Kitts and Nevis', 'KNA', 'North America', 'XCD', '+1-869', '🇰🇳', false),
('KP', 'Korea, Democratic People''s Republic of', 'PRK', 'Asia', 'KPW', '+850', '🇰🇵', false),
('KR', 'Korea, Republic of', 'KOR', 'Asia', 'KRW', '+82', '🇰🇷', false),
('KW', 'Kuwait', 'KWT', 'Asia', 'KWD', '+965', '🇰🇼', false),
('KY', 'Cayman Islands', 'CYM', 'North America', 'KYD', '+1-345', '🇰🇾', false),
('KZ', 'Kazakhstan', 'KAZ', 'Asia', 'KZT', '+7', '🇰🇿', false),
('LA', 'Lao People''s Democratic Republic', 'LAO', 'Asia', 'LAK', '+856', '🇱🇦', false),
('LB', 'Lebanon', 'LBN', 'Asia', 'LBP', '+961', '🇱🇧', false),
('LC', 'Saint Lucia', 'LCA', 'North America', 'XCD', '+1-758', '🇱🇨', false),
('LI', 'Liechtenstein', 'LIE', 'Europe', 'CHF', '+423', '🇱🇮', false),
('LK', 'Sri Lanka', 'LKA', 'Asia', 'LKR', '+94', '🇱🇰', false),
('LR', 'Liberia', 'LBR', 'Africa', 'LRD', '+231', '🇱🇷', false),
('LS', 'Lesotho', 'LSO', 'Africa', 'LSL', '+266', '🇱🇸', false),
('LT', 'Lithuania', 'LTU', 'Europe', 'EUR', '+370', '🇱🇹', false),
('LU', 'Luxembourg', 'LUX', 'Europe', 'EUR', '+352', '🇱🇺', false),
('LV', 'Latvia', 'LVA', 'Europe', 'EUR', '+371', '🇱🇻', false),
('LY', 'Libya', 'LBY', 'Africa', 'LYD', '+218', '🇱🇾', false),
('MA', 'Morocco', 'MAR', 'Africa', 'MAD', '+212', '🇲🇦', false),
('MC', 'Monaco', 'MCO', 'Europe', 'EUR', '+377', '🇲🇨', false),
('MD', 'Moldova, Republic of', 'MDA', 'Europe', 'MDL', '+373', '🇲🇩', false),
('ME', 'Montenegro', 'MNE', 'Europe', 'EUR', '+382', '🇲🇪', false),
('MF', 'Saint Martin (French part)', 'MAF', 'North America', 'EUR', '+590', '🇲🇫', false),
('MG', 'Madagascar', 'MDG', 'Africa', 'MGA', '+261', '🇲🇬', false),
('MH', 'Marshall Islands', 'MHL', 'Oceania', 'USD', '+692', '🇲🇭', false),
('MK', 'North Macedonia', 'MKD', 'Europe', 'MKD', '+389', '🇲🇰', false),
('ML', 'Mali', 'MLI', 'Africa', 'XOF', '+223', '🇲🇱', false),
('MM', 'Myanmar', 'MMR', 'Asia', 'MMK', '+95', '🇲🇲', false),
('MN', 'Mongolia', 'MNG', 'Asia', 'MNT', '+976', '🇲🇳', false),
('MO', 'Macao', 'MAC', 'Asia', 'MOP', '+853', '🇲🇴', false),
('MP', 'Northern Mariana Islands', 'MNP', 'Oceania', 'USD', '+1-670', '🇲🇵', false),
('MQ', 'Martinique', 'MTQ', 'North America', 'EUR', '+596', '🇲🇶', false),
('MR', 'Mauritania', 'MRT', 'Africa', 'MRU', '+222', '🇲🇷', false),
('MS', 'Montserrat', 'MSR', 'North America', 'XCD', '+1-664', '🇲🇸', false),
('MT', 'Malta', 'MLT', 'Europe', 'EUR', '+356', '🇲🇹', false),
('MU', 'Mauritius', 'MUS', 'Africa', 'MUR', '+230', '🇲🇺', false),
('MV', 'Maldives', 'MDV', 'Asia', 'MVR', '+960', '🇲🇻', false),
('MW', 'Malawi', 'MWI', 'Africa', 'MWK', '+265', '🇲🇼', false),
('MX', 'Mexico', 'MEX', 'North America', 'MXN', '+52', '🇲🇽', false),
('MY', 'Malaysia', 'MYS', 'Asia', 'MYR', '+60', '🇲🇾', false),
('MZ', 'Mozambique', 'MOZ', 'Africa', 'MZN', '+258', '🇲🇿', false),
('NA', 'Namibia', 'NAM', 'Africa', 'NAD', '+264', '🇳🇦', false),
('NC', 'New Caledonia', 'NCL', 'Oceania', 'XPF', '+687', '🇳🇨', false),
('NE', 'Niger', 'NER', 'Africa', 'XOF', '+227', '🇳🇪', false),
('NF', 'Norfolk Island', 'NFK', 'Oceania', 'AUD', '+672', '🇳🇫', false),
('NG', 'Nigeria', 'NGA', 'Africa', 'NGN', '+234', '🇳🇬', false),
('NI', 'Nicaragua', 'NIC', 'North America', 'NIO', '+505', '🇳🇮', false),
('NL', 'Netherlands', 'NLD', 'Europe', 'EUR', '+31', '🇳🇱', false),
('NO', 'Norway', 'NOR', 'Europe', 'NOK', '+47', '🇳🇴', false),
('NP', 'Nepal', 'NPL', 'Asia', 'NPR', '+977', '🇳🇵', false),
('NR', 'Nauru', 'NRU', 'Oceania', 'AUD', '+674', '🇳🇷', false),
('NU', 'Niue', 'NIU', 'Oceania', 'NZD', '+683', '🇳🇺', false),
('NZ', 'New Zealand', 'NZL', 'Oceania', 'NZD', '+64', '🇳🇿', false),
('OM', 'Oman', 'OMN', 'Asia', 'OMR', '+968', '🇴🇲', false),
('PA', 'Panama', 'PAN', 'North America', 'PAB', '+507', '🇵🇦', false),
('PE', 'Peru', 'PER', 'South America', 'PEN', '+51', '🇵🇪', false),
('PF', 'French Polynesia', 'PYF', 'Oceania', 'XPF', '+689', '🇵🇫', false),
('PG', 'Papua New Guinea', 'PNG', 'Oceania', 'PGK', '+675', '🇵🇬', false),
('PH', 'Philippines', 'PHL', 'Asia', 'PHP', '+63', '🇵🇭', false),
('PK', 'Pakistan', 'PAK', 'Asia', 'PKR', '+92', '🇵🇰', false),
('PL', 'Poland', 'POL', 'Europe', 'PLN', '+48', '🇵🇱', false),
('PM', 'Saint Pierre and Miquelon', 'SPM', 'North America', 'EUR', '+508', '🇵🇲', false),
('PN', 'Pitcairn', 'PCN', 'Oceania', 'NZD', '+64', '🇵🇳', false),
('PR', 'Puerto Rico', 'PRI', 'North America', 'USD', '+1-787', '🇵🇷', false),
('PS', 'Palestine, State of', 'PSE', 'Asia', 'ILS', '+970', '🇵🇸', false),
('PT', 'Portugal', 'PRT', 'Europe', 'EUR', '+351', '🇵🇹', false),
('PW', 'Palau', 'PLW', 'Oceania', 'USD', '+680', '🇵🇼', false),
('PY', 'Paraguay', 'PRY', 'South America', 'PYG', '+595', '🇵🇾', false),
('QA', 'Qatar', 'QAT', 'Asia', 'QAR', '+974', '🇶🇦', false),
('RE', 'Réunion', 'REU', 'Africa', 'EUR', '+262', '🇷🇪', false),
('RO', 'Romania', 'ROU', 'Europe', 'RON', '+40', '🇷🇴', false),
('RS', 'Serbia', 'SRB', 'Europe', 'RSD', '+381', '🇷🇸', false),
('RU', 'Russian Federation', 'RUS', 'Europe', 'RUB', '+7', '🇷���', false),
('RW', 'Rwanda', 'RWA', 'Africa', 'RWF', '+250', '🇷🇼', false),
('SA', 'Saudi Arabia', 'SAU', 'Asia', 'SAR', '+966', '🇸🇦', true),
('SB', 'Solomon Islands', 'SLB', 'Oceania', 'SBD', '+677', '🇸🇧', false),
('SC', 'Seychelles', 'SYC', 'Africa', 'SCR', '+248', '🇸🇨', false),
('SD', 'Sudan', 'SDN', 'Africa', 'SDG', '+249', '🇸🇩', false),
('SE', 'Sweden', 'SWE', 'Europe', 'SEK', '+46', '🇸🇪', false),
('SG', 'Singapore', 'SGP', 'Asia', 'SGD', '+65', '🇸🇬', true),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', 'Africa', 'SHP', '+290', '🇸🇭', false),
('SI', 'Slovenia', 'SVN', 'Europe', 'EUR', '+386', '🇸🇮', false),
('SJ', 'Svalbard and Jan Mayen', 'SJM', 'Europe', 'NOK', '+47', '🇸🇯', false),
('SK', 'Slovakia', 'SVK', 'Europe', 'EUR', '+421', '🇸🇰', false),
('SL', 'Sierra Leone', 'SLE', 'Africa', 'SLL', '+232', '🇸🇱', false),
('SM', 'San Marino', 'SMR', 'Europe', 'EUR', '+378', '🇸🇲', false),
('SN', 'Senegal', 'SEN', 'Africa', 'XOF', '+221', '🇸🇳', false),
('SO', 'Somalia', 'SOM', 'Africa', 'SOS', '+252', '🇸🇴', false),
('SR', 'Suriname', 'SUR', 'South America', 'SRD', '+597', '🇸🇷', false),
('SS', 'South Sudan', 'SSD', 'Africa', 'SSP', '+211', '🇸🇸', false),
('ST', 'Sao Tome and Principe', 'STP', 'Africa', 'STN', '+239', '🇸🇹', false),
('SV', 'El Salvador', 'SLV', 'North America', 'USD', '+503', '🇸🇻', false),
('SX', 'Sint Maarten (Dutch part)', 'SXM', 'North America', 'ANG', '+1-721', '��🇽', false),
('SY', 'Syrian Arab Republic', 'SYR', 'Asia', 'SYP', '+963', '🇸🇾', false),
('SZ', 'Eswatini', 'SWZ', 'Africa', 'SZL', '+268', '🇸🇿', false),
('TC', 'Turks and Caicos Islands', 'TCA', 'North America', 'USD', '+1-649', '🇹🇨', false),
('TD', 'Chad', 'TCD', 'Africa', 'XAF', '+235', '🇹🇩', false),
('TF', 'French Southern Territories', 'ATF', 'Antarctica', 'EUR', NULL, '🇹🇫', false),
('TG', 'Togo', 'TGO', 'Africa', 'XOF', '+228', '🇹🇬', false),
('TH', 'Thailand', 'THA', 'Asia', 'THB', '+66', '🇹🇭', true),
('TJ', 'Tajikistan', 'TJK', 'Asia', 'TJS', '+992', '🇹🇯', false),
('TK', 'Tokelau', 'TKL', 'Oceania', 'NZD', '+690', '🇹🇰', false),
('TL', 'Timor-Leste', 'TLS', 'Asia', 'USD', '+670', '🇹🇱', false),
('TM', 'Turkmenistan', 'TKM', 'Asia', 'TMT', '+993', '🇹🇲', false),
('TN', 'Tunisia', 'TUN', 'Africa', 'TND', '+216', '🇹🇳', false),
('TO', 'Tonga', 'TON', 'Oceania', 'TOP', '+676', '🇹🇴', false),
('TR', 'Turkey', 'TUR', 'Asia', 'TRY', '+90', '🇹🇷', false),
('TT', 'Trinidad and Tobago', 'TTO', 'North America', 'TTD', '+1-868', '🇹🇹', false),
('TV', 'Tuvalu', 'TUV', 'Oceania', 'AUD', '+688', '🇹🇻', false),
('TW', 'Taiwan, Province of China', 'TWN', 'Asia', 'TWD', '+886', '🇹🇼', false),
('TZ', 'Tanzania, United Republic of', 'TZA', 'Africa', 'TZS', '+255', '🇹🇿', false),
('UA', 'Ukraine', 'UKR', 'Europe', 'UAH', '+380', '🇺🇦', false),
('UG', 'Uganda', 'UGA', 'Africa', 'UGX', '+256', '🇺🇬', false),
('UM', 'United States Minor Outlying Islands', 'UMI', 'Oceania', 'USD', '+1', '🇺🇲', false),
('US', 'United States', 'USA', 'North America', 'USD', '+1', '🇺🇸', true),
('UY', 'Uruguay', 'URY', 'South America', 'UYU', '+598', '🇺🇾', false),
('UZ', 'Uzbekistan', 'UZB', 'Asia', 'UZS', '+998', '🇺🇿', false),
('VA', 'Holy See (Vatican City State)', 'VAT', 'Europe', 'EUR', '+39', '🇻🇦', false),
('VC', 'Saint Vincent and the Grenadines', 'VCT', 'North America', 'XCD', '+1-784', '🇻🇨', false),
('VE', 'Venezuela, Bolivarian Republic of', 'VEN', 'South America', 'VES', '+58', '🇻🇪', false),
('VG', 'Virgin Islands, British', 'VGB', 'North America', 'USD', '+1-284', '🇻🇬', false),
('VI', 'Virgin Islands, U.S.', 'VIR', 'North America', 'USD', '+1-340', '🇻🇮', false),
('VN', 'Viet Nam', 'VNM', 'Asia', 'VND', '+84', '🇻🇳', false),
('VU', 'Vanuatu', 'VUT', 'Oceania', 'VUV', '+678', '🇻🇺', false),
('WF', 'Wallis and Futuna', 'WLF', 'Oceania', 'XPF', '+681', '🇼🇫', false),
('WS', 'Samoa', 'WSM', 'Oceania', 'WST', '+685', '🇼🇸', false),
('YE', 'Yemen', 'YEM', 'Asia', 'YER', '+967', '🇾🇪', false),
('YT', 'Mayotte', 'MYT', 'Africa', 'EUR', '+262', '🇾🇹', false),
('ZA', 'South Africa', 'ZAF', 'Africa', 'ZAR', '+27', '🇿🇦', false),
('ZM', 'Zambia', 'ZMB', 'Africa', 'ZMW', '+260', '🇿🇲', false),
('ZW', 'Zimbabwe', 'ZWE', 'Africa', 'ZWL', '+263', '🇿🇼', false);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_countries_iso2 ON public.countries(iso2);
CREATE INDEX IF NOT EXISTS idx_countries_popular ON public.countries(popular) WHERE popular = true;
CREATE INDEX IF NOT EXISTS idx_countries_continent ON public.countries(continent);

-- Add foreign key constraints to link with existing tables
DO $$ 
BEGIN
    -- Link users.nationality_iso2 to countries.iso2
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_nationality_iso2') THEN
        ALTER TABLE users ADD CONSTRAINT fk_users_nationality_iso2
        FOREIGN KEY (nationality_iso2) REFERENCES public.countries(iso2);
    END IF;
    
    -- Link faredown.addresses.country_iso2 to countries.iso2
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_addresses_country_iso2') THEN
        ALTER TABLE faredown.addresses ADD CONSTRAINT fk_addresses_country_iso2
        FOREIGN KEY (country_iso2) REFERENCES public.countries(iso2);
    END IF;
    
    -- Link faredown.travelers.nationality_iso2 to countries.iso2
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_travelers_nationality_iso2') THEN
        ALTER TABLE faredown.travelers ADD CONSTRAINT fk_travelers_nationality_iso2
        FOREIGN KEY (nationality_iso2) REFERENCES public.countries(iso2);
    END IF;
    
    -- Link faredown.passports.issuing_country to countries.iso2
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_passports_issuing_country') THEN
        ALTER TABLE faredown.passports ADD CONSTRAINT fk_passports_issuing_country
        FOREIGN KEY (issuing_country) REFERENCES public.countries(iso2);
    END IF;
EXCEPTION
    WHEN others THEN
        -- If any FK constraint fails (e.g., invalid data exists), log but continue
        RAISE NOTICE 'Warning: Some foreign key constraints could not be added. Check for invalid country codes in existing data.';
END $$;

-- Verify the seed
SELECT 'Countries seeded successfully!' as status, COUNT(*) as total_countries FROM public.countries;
SELECT 'Popular countries:' as info, iso2, name FROM public.countries WHERE popular = true ORDER BY name;
