services:
  - type: web
    name: faredown-backend-api
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: faredown-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: BARGAIN_SESSION_TIMEOUT
        value: 600
      - key: MAX_BARGAIN_ATTEMPTS
        value: 3
      - key: MIN_MARKUP_PERCENTAGE
        value: 5.0
      - key: MAX_MARKUP_PERCENTAGE
        value: 20.0
    healthCheckPath: /health

databases:
  - name: faredown-postgres
    databaseName: faredown_production
    user: faredown_user
    plan: starter
